- name: My first play
  hosts: dev-machine
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
      become: true

    - name: Check if Docker is already installed
      ansible.builtin.command: docker --version
      register: docker_installed
      failed_when: false
      changed_when: false

    - name: Install prerequisite packages for Docker
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: true
      become: true
      when: docker_installed.rc != 0

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: true
      when: docker_installed.rc != 0

    - name: Add Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
      become: true
      when: docker_installed.rc != 0

    - name: Get architecture for Docker repository
      ansible.builtin.command: dpkg --print-architecture
      register: system_arch
      changed_when: false
      when: docker_installed.rc != 0

    - name: Get OS version codename
      ansible.builtin.command: lsb_release -cs
      register: version_codename
      changed_when: false
      when: docker_installed.rc != 0

    - name: Add Docker repository to apt sources
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/debian {{ version_codename.stdout }} stable
        state: present
        filename: docker
      become: true
      when: docker_installed.rc != 0

    - name: Update apt cache after adding Docker repository
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: docker_installed.rc != 0

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      become: true
      when: docker_installed.rc != 0
