name: Run Ansible playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to dev server
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.HETZNER_BARE_METAL_GITHUB_ACTIONS_SSH_PRIVATE_KEY }}

      - name: Parse server IP from inventory
        id: parse-inventory
        run: |
          SERVER_IP=$(grep -A 3 "machine-1:" inventory.yaml | grep "ansible_host:" | awk '{print $2}')
          echo "server_ip=$SERVER_IP" >> $GITHUB_OUTPUT
          echo "Parsed server IP: $SERVER_IP"

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ steps.parse-inventory.outputs.server_ip }} >> ~/.ssh/known_hosts

      - name: Check server connectivity
        run: |
          ssh -o ConnectTimeout=10 root@${{ steps.parse-inventory.outputs.server_ip }} "echo 'Server connection successful'"

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible --version

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory.yaml playbook.yaml -u root

